import type { Metadata } from "next";
import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { requireProfile } from "@/lib/session";
import { PageHeader } from "@/components/ui/PageHeader";
import { Card,CardBody,CardHeader } from "@/components/ui/Card";
import { addSalesActivityAction,updateSalesPlanAction } from "../actions";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Sales Opportunity — ReliefBridge"};
const PLATFORM_ORGANIZATION_ID="9f3cb5cc-aa6f-44cb-8aa9-b0a7bc505142";
function fmt(v:string|null){if(!v)return "Not recorded";const d=new Date(v);return Number.isNaN(d.getTime())?"Not recorded":new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(d);}
export default async function OpportunityPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string}>}){
 const profile=await requireProfile(),role=typeof profile.role==="string"?profile.role.trim().toLowerCase():"";if(profile.organization_id!==PLATFORM_ORGANIZATION_ID||!(role==="owner"||role==="admin"))redirect("/app");
 const {id}=await params,sp=await searchParams,supabase=await createSupabaseServerClient();
 const [{data:o},{data:a}]=await Promise.all([supabase.from("sales_opportunities").select("*").eq("id",id).maybeSingle(),supabase.from("sales_activities").select("id,activity_type,summary,details,occurred_at").eq("opportunity_id",id).order("occurred_at",{ascending:false}).limit(100)]);
 if(!o)notFound();const activities=(a??[]) as Array<{id:string;activity_type:string;summary:string;details:string|null;occurred_at:string}>;
 const name=[o.contact_first_name,o.contact_last_name].filter(Boolean).join(" ");
 return <><PageHeader eyebrow="ReliefBridge Management" title={o.organization_name} subtitle={`${name||"Contact"}${o.role_title?" · "+o.role_title:""} · ${o.stage}`} breadcrumbs={[{label:"Sales Pipeline",href:"/app/platform/sales"},{label:o.organization_name}]} actions={<Link href="/app/platform/sales" className="inline-flex h-11 items-center rounded-sm border border-line bg-white px-4 text-[13px] font-bold text-navy hover:no-underline">Back to pipeline</Link>}/>
 <div className="space-y-6 px-6 py-8 md:px-10">{sp.saved==="1"&&<div className="rounded-md border border-green/25 bg-green/10 px-5 py-4 text-[13px] font-semibold text-green">Opportunity updated.</div>}
 <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="space-y-6"><Card><CardHeader title="Opportunity profile" subtitle="Internal commercial view of this prospective ReliefBridge organization."/><CardBody className="grid gap-5 sm:grid-cols-2"><div><b className="text-navy">Contact</b><div className="mt-1 text-sm text-ink-2">{name||"Not recorded"}</div></div><div><b className="text-navy">Email</b><a className="mt-1 block text-sm text-blue" href={"mailto:"+o.contact_email}>{o.contact_email}</a></div><div><b className="text-navy">Phone</b><div className="mt-1 text-sm text-ink-2">{o.contact_phone||"Not recorded"}</div></div><div><b className="text-navy">Source</b><div className="mt-1 text-sm text-ink-2">{o.source}</div></div><div><b className="text-navy">Recovery focus</b><div className="mt-1 text-sm text-ink-2">{o.recovery_focus||"Not recorded"}</div></div><div><b className="text-navy">Last activity</b><div className="mt-1 text-sm text-ink-2">{fmt(o.last_activity_at)}</div></div></CardBody></Card>
 <Card><CardHeader title="Activity timeline" subtitle="Chronological sales history for this opportunity."/><CardBody>{activities.length===0?<div className="text-sm text-ink-3">No activity recorded yet.</div>:<div className="space-y-4">{activities.map(x=><div key={x.id} className="border-l-2 border-blue/20 pl-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-surface-2 px-2 py-1 text-[10.5px] font-bold text-navy">{x.activity_type}</span><span className="text-[11.5px] text-ink-3">{fmt(x.occurred_at)}</span></div><div className="mt-2 text-[13.5px] font-semibold text-ink">{x.summary}</div>{x.details&&<div className="mt-1 whitespace-pre-wrap text-[12.5px] leading-5 text-ink-2">{x.details}</div>}</div>)}</div>}</CardBody></Card></div>
 <aside className="space-y-6"><Card><CardHeader title="Next action" subtitle="Keep the opportunity moving without losing the follow-up."/><CardBody><form action={updateSalesPlanAction} className="space-y-4"><input type="hidden" name="opportunity_id" value={id}/><div><label className="mb-2 block text-[12.5px] font-bold text-navy">Next action</label><input name="next_action" defaultValue={o.next_action??""} maxLength={500} className="h-11 w-full rounded-sm border border-line px-3 text-sm"/></div><div><label className="mb-2 block text-[12.5px] font-bold text-navy">Follow-up date/time</label><input type="datetime-local" name="next_action_at" className="h-11 w-full rounded-sm border border-line px-3 text-sm"/></div><button className="h-11 w-full rounded-sm bg-blue text-sm font-bold text-white">Save next action</button></form></CardBody></Card>
 <Card><CardHeader title="Add activity" subtitle="Record calls, emails, demos, quotes, evaluations, and internal notes."/><CardBody><form action={addSalesActivityAction} className="space-y-4"><input type="hidden" name="opportunity_id" value={id}/><select name="activity_type" className="h-11 w-full rounded-sm border border-line px-3 text-sm">{["Email","Phone","Demo","Evaluation","Quote","Note","Follow-Up","Other"].map(x=><option key={x}>{x}</option>)}</select><input name="summary" required maxLength={300} placeholder="Short activity summary" className="h-11 w-full rounded-sm border border-line px-3 text-sm"/><textarea name="details" maxLength={5000} rows={5} placeholder="Optional details" className="w-full rounded-sm border border-line px-3 py-3 text-sm"/><button className="h-11 w-full rounded-sm bg-navy text-sm font-bold text-white">Add to timeline</button></form></CardBody></Card></aside></div></div></>;
}