"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { ComponentType, SVGProps } from "react";
import { Logo } from "@/components/brand/Logo";
import { Icons } from "@/components/ui/Icons";
import { cn, initials } from "@/lib/utils";
type Item={label:string;href:string;icon:ComponentType<SVGProps<SVGSVGElement>>};
const orgGroups=[{title:"Workspace",items:[["Overview","/app",Icons.Dashboard],["Survivors","/app/survivors",Icons.Survivors],["Recovery cases","/app/cases",Icons.Cases],["Unmet needs","/app/unmet-needs",Icons.Needs]]},{title:"Network",items:[["Referral exchange","/app/referrals",Icons.Referrals],["Partner organizations","/app/partners",Icons.Partners]]},{title:"Insights",items:[["Reports","/app/reports",Icons.Reports]]},{title:"Account",items:[["Settings","/app/settings/organization",Icons.Settings]]}];
const staffGroups=[{title:"My Work",items:[["Overview","/app",Icons.Dashboard],["Survivors","/app/survivors",Icons.Survivors],["Recovery cases","/app/cases",Icons.Cases],["Unmet needs","/app/unmet-needs",Icons.Needs],["Referrals","/app/referrals",Icons.Referrals]]},{title:"Communication",items:[["Internal Mail","/app/mail",Icons.Mail]]},{title:"Insights",items:[["Reports","/app/reports",Icons.Reports]]},{title:"Account",items:[["My Profile","/app/settings/profile",Icons.Settings]]}];
const adminGroups=[{title:"Platform",items:[["Command Center","/app",Icons.Dashboard],["Organizations","/app/platform/organizations",Icons.Building],["Demo Hub","/app/demo-hub",Icons.Reports],["Demo requests","/app/demo-requests",Icons.Mail],["Network Activity","/app/platform/network-activity",Icons.Referrals]]},{title:"Operations",items:[["Survivors","/app/survivors",Icons.Survivors],["Recovery cases","/app/cases",Icons.Cases],["Unmet needs","/app/unmet-needs",Icons.Needs],["Referrals","/app/referrals",Icons.Referrals]]},{title:"Administration",items:[["Staff Management","/app/platform/staff",Icons.Partners],["Access Control","/app/platform/access-control",Icons.Settings],["Activity Log","/app/platform/activity",Icons.Reports],["System Health","/app/platform/system-health",Icons.Dashboard]]},{title:"Insights",items:[["Reports","/app/reports",Icons.Reports]]},{title:"Account",items:[["My Profile","/app/settings/profile",Icons.Settings]]}];
export function Sidebar({user,orgName,isManagedDemo=false,isPlatformAdmin=false,isPlatformStaff=false}:{user:{name:string;email:string;role:string};orgName:string;isManagedDemo?:boolean;isPlatformAdmin?:boolean;isPlatformStaff?:boolean}){
 const pathname=usePathname(); let groups=isPlatformAdmin?adminGroups:isPlatformStaff?staffGroups:orgGroups;
 const isLouisianaDemo=orgName.trim().toLowerCase()==="louisiana voad demo workspace";
 if(isManagedDemo){groups=orgGroups.filter(g=>g.title!=="Account");if(isLouisianaDemo)groups=[...groups,{title:"Louisiana VOAD",items:[["Louisiana VOAD Report","/app/reports/louisiana-voad",Icons.Reports]]}];}
 return <aside className="sticky top-0 hidden h-screen w-[268px] shrink-0 flex-col border-r border-line bg-surface-2 lg:flex">
 <div className="shrink-0 border-b border-line px-5 py-5"><Link href="/app" className="block hover:no-underline"><Logo size="sm"/></Link></div>
 <div className="shrink-0 px-3 py-3"><div className="rounded-sm border border-line bg-surface px-3 py-2.5"><div className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-sm bg-navy text-[11px] font-bold text-white">{isPlatformAdmin?"RB":initials(orgName.split(" ")[0],orgName.split(" ")[1])}</span><div className="min-w-0"><div className="truncate text-[12.5px] font-bold text-navy">{isPlatformAdmin?"ReliefBridge Administration":isPlatformStaff?"ReliefBridge Staff":orgName}</div><div className="truncate text-[11px] text-ink-3">{isPlatformAdmin?"Platform control center":isPlatformStaff?"Internal operations workspace":isManagedDemo?"Managed demo · Read-only":"Active organization"}</div></div></div></div></div>
 <nav className="min-h-0 flex-1 overflow-y-auto px-3 pb-6">{groups.map(g=><div key={g.title} className="mb-3"><div className="px-3 pb-1.5 text-[10.5px] font-bold uppercase tracking-[0.14em] text-ink-3">{g.title}</div><ul className="space-y-0.5">{g.items.map(([label,href,Icon])=>{const active=pathname===href||(href!=="/app"&&pathname.startsWith(href+"/"));return <li key={href as string}><Link href={href as string} className={cn("group flex items-center gap-3 rounded-sm px-3 py-2 text-[13px] font-medium hover:no-underline",active?"bg-blue text-white":"text-ink-2 hover:bg-surface hover:text-navy")}><Icon className="h-[18px] w-[18px] shrink-0"/><span>{label as string}</span></Link></li>})}</ul></div>)}</nav>
 <div className="shrink-0 border-t border-line px-3 py-3"><Link href={isManagedDemo?"/app":"/app/settings/profile"} className="flex items-center gap-3 rounded-sm px-2 py-2 hover:bg-surface hover:no-underline"><span className="grid h-9 w-9 place-items-center rounded-sm bg-navy text-[12px] font-bold text-white">{initials(user.name.split(" ")[0],user.name.split(" ")[1])}</span><div className="min-w-0 flex-1"><div className="truncate text-[13px] font-bold text-navy">{user.name}</div><div className="truncate text-[11.5px] text-ink-3">{isPlatformAdmin&&user.role.toLowerCase()==="owner"?"Super Admin":user.role}</div></div><Icons.ChevronRight className="h-4 w-4"/></Link><form action="/auth/signout" method="post"><button className="mt-1 inline-flex w-full items-center gap-2 rounded-sm px-3 py-2 text-[12.5px] font-semibold text-ink-3 hover:text-red"><Icons.Logout className="h-4 w-4"/>Sign out</button></form></div>
 </aside>
}