"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { ComponentType, SVGProps } from "react";
import { Logo } from "@/components/brand/Logo";
import { Icons } from "@/components/ui/Icons";
import { cn, initials } from "@/lib/utils";
type Item={label:string;href:string;icon:ComponentType<SVGProps<SVGSVGElement>>};
type Group={title:string;items:Item[]};
const orgGroups:Group[]=[{title:"Workspace",items:[{label:"Overview",href:"/app",icon:Icons.Dashboard},{label:"Survivors",href:"/app/survivors",icon:Icons.Survivors},{label:"Recovery cases",href:"/app/cases",icon:Icons.Cases},{label:"Unmet needs",href:"/app/unmet-needs",icon:Icons.Needs}]},{title:"Network",items:[{label:"Referral exchange",href:"/app/referrals",icon:Icons.Referrals},{label:"Partner organizations",href:"/app/partners",icon:Icons.Partners}]},{title:"Communication",items:[{label:"Mail",href:"/app/mail",icon:Icons.Mail}]},{title:"Insights",items:[{label:"Reports",href:"/app/reports",icon:Icons.Reports}]},{title:"Account",items:[{label:"Settings",href:"/app/settings/organization",icon:Icons.Settings}]}];
const staffGroups:Group[]=[{title:"My Work",items:[{label:"Overview",href:"/app",icon:Icons.Dashboard},{label:"Survivors",href:"/app/survivors",icon:Icons.Survivors},{label:"Recovery cases",href:"/app/cases",icon:Icons.Cases},{label:"Unmet needs",href:"/app/unmet-needs",icon:Icons.Needs},{label:"Referrals",href:"/app/referrals",icon:Icons.Referrals}]},{title:"Communication",items:[{label:"Mail",href:"/app/mail",icon:Icons.Mail}]},{title:"Insights",items:[{label:"Reports",href:"/app/reports",icon:Icons.Reports}]},{title:"Account",items:[{label:"My Profile",href:"/app/settings/profile",icon:Icons.Settings}]}];
const adminGroups:Group[]=[{title:"Platform",items:[{label:"Command Center",href:"/app",icon:Icons.Dashboard},{label:"Organizations",href:"/app/platform/organizations",icon:Icons.Building},{label:"Demo Hub",href:"/app/demo-hub",icon:Icons.Reports},{label:"Demo requests",href:"/app/demo-requests",icon:Icons.Mail},{label:"Sales Pipeline",href:"/app/platform/sales",icon:Icons.Reports},{label:"Network Activity",href:"/app/platform/network-activity",icon:Icons.Referrals}]},{title:"Operations",items:[{label:"Survivors",href:"/app/survivors",icon:Icons.Survivors},{label:"Recovery cases",href:"/app/cases",icon:Icons.Cases},{label:"Unmet needs",href:"/app/unmet-needs",icon:Icons.Needs},{label:"Referrals",href:"/app/referrals",icon:Icons.Referrals}]},{title:"Communication",items:[{label:"Mail",href:"/app/mail",icon:Icons.Mail}]},{title:"Administration",items:[{label:"Staff Management",href:"/app/platform/staff",icon:Icons.Partners},{label:"Work Assignments",href:"/app/platform/assignments",icon:Icons.Cases},{label:"Access Control",href:"/app/platform/access-control",icon:Icons.Settings},{label:"Activity Log",href:"/app/platform/activity",icon:Icons.Reports},{label:"System Health",href:"/app/platform/system-health",icon:Icons.Dashboard}]},{title:"Insights",items:[{label:"Reports",href:"/app/reports",icon:Icons.Reports}]},{title:"Account",items:[{label:"My Profile",href:"/app/settings/profile",icon:Icons.Settings}]}];
export function Sidebar({user,orgName,isManagedDemo=false,isPlatformAdmin=false,isPlatformStaff=false,isPlatformOwner=false,communicationsMode="off"}:{user:{name:string;email:string;role:string};orgName:string;isManagedDemo?:boolean;isPlatformAdmin?:boolean;isPlatformStaff?:boolean;isPlatformOwner?:boolean;communicationsMode?:string}){
 const pathname=usePathname(); let groups=isPlatformAdmin?adminGroups:isPlatformStaff?staffGroups:orgGroups;if(!isPlatformAdmin&&!isPlatformStaff&&communicationsMode==="off")groups=groups.filter(g=>g.title!=="Communication");if(isPlatformAdmin&&!isPlatformOwner)groups=adminGroups.map(g=>g.title==="Administration"?{...g,items:g.items.filter(i=>i.href!=="/app/platform/assignments")}:g);
 const isLouisianaDemo=orgName.trim().toLowerCase()==="louisiana voad demo workspace";
 if(isManagedDemo){groups=orgGroups.filter(g=>g.title!=="Account");if(isLouisianaDemo)groups=[...groups,{title:"Louisiana VOAD",items:[{label:"Louisiana VOAD Report",href:"/app/reports/louisiana-voad",icon:Icons.Reports}]}];}
 return <aside className="sticky top-0 hidden h-screen w-[268px] shrink-0 flex-col border-r border-line bg-surface-2 lg:flex">
 <div className="shrink-0 border-b border-line px-5 py-5"><Link href="/app" className="block hover:no-underline"><Logo size="sm"/></Link></div>
 <div className="shrink-0 px-3 py-3"><div className="rounded-sm border border-line bg-surface px-3 py-2.5"><div className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-sm bg-navy text-[11px] font-bold text-white">{isPlatformAdmin?"RB":initials(orgName.split(" ")[0],orgName.split(" ")[1])}</span><div className="min-w-0"><div className="truncate text-[12.5px] font-bold text-navy">{isPlatformAdmin?"ReliefBridge Administration":isPlatformStaff?"ReliefBridge Staff":orgName}</div><div className="truncate text-[11px] text-ink-3">{isPlatformAdmin?"Platform control center":isPlatformStaff?"Internal operations workspace":isManagedDemo?"Managed demo · Read-only":"Active organization"}</div></div></div></div></div>
 <nav className="min-h-0 flex-1 overflow-y-auto px-3 pb-6">{groups.map(g=><div key={g.title} className="mb-3"><div className="px-3 pb-1.5 text-[10.5px] font-bold uppercase tracking-[0.14em] text-ink-3">{g.title}</div><ul className="space-y-0.5">{g.items.map(({label,href,icon:Icon})=>{const active=pathname===href||(href!=="/app"&&pathname.startsWith(href+"/"));return <li key={href}><Link href={href} className={cn("group flex items-center gap-3 rounded-sm px-3 py-2 text-[13px] font-medium hover:no-underline",active?"bg-blue text-white":"text-ink-2 hover:bg-surface hover:text-navy")}><Icon className="h-[18px] w-[18px] shrink-0"/><span>{label}</span></Link></li>})}</ul></div>)}</nav>
 <div className="shrink-0 border-t border-line px-3 py-3"><Link href={isManagedDemo?"/app":"/app/settings/profile"} className="flex items-center gap-3 rounded-sm px-2 py-2 hover:bg-surface hover:no-underline"><span className="grid h-9 w-9 place-items-center rounded-sm bg-navy text-[12px] font-bold text-white">{initials(user.name.split(" ")[0],user.name.split(" ")[1])}</span><div className="min-w-0 flex-1"><div className="truncate text-[13px] font-bold text-navy">{user.name}</div><div className="truncate text-[11.5px] text-ink-3">{isPlatformAdmin&&user.role.toLowerCase()==="owner"?"Super Admin":user.role}</div></div><Icons.ChevronRight className="h-4 w-4"/></Link><form action="/auth/signout" method="post"><button className="mt-1 inline-flex w-full items-center gap-2 rounded-sm px-3 py-2 text-[12.5px] font-semibold text-ink-3 hover:text-red"><Icons.Logout className="h-4 w-4"/>Sign out</button></form></div>
 </aside>
}