import { redirect } from "next/navigation";
import { requireProfile } from "@/lib/session";
import { createSupabaseServerClient } from "@/lib/supabase-server";
import { PageHeader } from "@/components/ui/PageHeader";
import { Card,CardBody,CardHeader } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { createStaff,staffControl } from "./actions";
const PLATFORM="9f3cb5cc-aa6f-44cb-8aa9-b0a7bc505142";
const when=(v:string|null)=>v?new Date(v).toLocaleString():"Never";
const roleLabel=(v:string)=>{const r=v.toLowerCase();return r==="owner"?"Super Admin":r==="admin"?"Admin":r==="manager"?"Manager":r==="staff"?"Staff":v};

export default async function StaffPage(){
 const p=await requireProfile(),role=(p.role??"").toLowerCase();
 if(p.organization_id!==PLATFORM||!["owner","admin"].includes(role))redirect("/app");
 const s=await createSupabaseServerClient();
 const {data:staff}=await s.from("profiles").select("id,first_name,last_name,email,personal_email,title,department,staff_id,role,access_status,must_set_password,created_at,last_access_at,invited_at").eq("organization_id",PLATFORM).order("created_at");
 return <><PageHeader eyebrow="Administration" title="Staff Management" subtitle="Create and govern ReliefBridge internal staff identities without exposing the protected Super Admin role."/>
 <div className="space-y-6 px-6 py-8 md:px-10">
 {role==="owner"&&<Card><CardHeader title="Onboard staff member" subtitle="ReliefBridge generates the corporate login automatically and sends a one-time activation link to the employee's personal email."/><CardBody><form action={createStaff} className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><input name="first_name" required placeholder="Legal first name" className="h-11 rounded-sm border border-line px-3"/><input name="last_name" required placeholder="Legal last name" className="h-11 rounded-sm border border-line px-3"/><input name="personal_email" type="email" required placeholder="Personal email" className="h-11 rounded-sm border border-line px-3"/><input name="title" required placeholder="Job title" className="h-11 rounded-sm border border-line px-3"/><input name="department" required placeholder="Department / workstream" className="h-11 rounded-sm border border-line px-3"/><select name="role" required defaultValue="staff" className="h-11 rounded-sm border border-line bg-white px-3"><option value="staff">Staff</option><option value="manager">Manager</option><option value="admin">Admin</option></select><div className="md:col-span-2 xl:col-span-3"><Button type="submit" size="sm">Create staff account and send activation</Button></div></form></CardBody></Card>}
 <Card><CardHeader title="ReliefBridge workforce" subtitle="Corporate identity, role, lifecycle state, and last access are controlled here. Historical staff records are preserved."/><CardBody padded={false}><div className="divide-y divide-line">{(staff??[]).map(x=>{const r=String(x.role||"");const owner=r.toLowerCase()==="owner",invited=x.access_status==="invited"&&x.must_set_password,disabled=x.access_status==="disabled";return <div key={x.id} className="flex flex-wrap items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><div className="font-bold text-navy">{[x.first_name,x.last_name].filter(Boolean).join(" ")||x.email}</div><div className="mt-1 text-[12.5px] text-ink-2">{roleLabel(r)}{x.title?" · "+x.title:""}{x.department?" · "+x.department:""}</div><div className="mt-1 text-[12px] text-ink-3">{x.email||"No corporate email"}{x.staff_id?" · "+x.staff_id:""} · <span className="font-semibold uppercase">{x.access_status}</span></div><div className="mt-1 text-[11.5px] text-ink-3">Last access: {when(x.last_access_at)}{invited&&x.invited_at?" · Invited "+when(x.invited_at):""}</div></div>{role==="owner"&&!owner&&<div className="flex flex-wrap gap-2">{invited&&<form action={staffControl}><input type="hidden" name="user_id" value={x.id}/><input type="hidden" name="action" value="resend_activation"/><Button type="submit" variant="outline" size="sm">Resend activation</Button></form>}{!invited&&<form action={staffControl}><input type="hidden" name="user_id" value={x.id}/><input type="hidden" name="action" value={disabled?"reactivate":"disable"}/><Button type="submit" variant="outline" size="sm">{disabled?"Reactivate":"Suspend"}</Button></form>}<form action={staffControl}><input type="hidden" name="user_id" value={x.id}/><input type="hidden" name="action" value="deactivate"/><Button type="submit" variant="danger" size="sm">Deactivate</Button></form></div>}</div>})}</div></CardBody></Card>
 </div></>;
}
